import bge

def main():
	
	cont = bge.logic.getCurrentController()
	own = cont.owner

	High = cont.sensors["highhover"].owner
	Low = cont.sensors["lowhover"].owner
	Save = cont.sensors["saveover"].owner
	Return = cont.sensors["returnover"].owner
	tensixeight = cont.sensors["1024x768hover"].owner
	elevensixfour = cont.sensors["1152x864hover"].owner
	twelvesixeight = cont.sensors["1280x768hover"].owner
	twelvezero = cont.sensors["1280x800hover"].owner
	twelvetwofour = cont.sensors["1280x1024hover"].owner
	thirteensixeight = cont.sensors["1366x768hover"].owner
	fourteenten = cont.sensors["1440x900hover"].owner
	sixteenfivezero = cont.sensors["1680x1050hover"].owner
	nineteenzero = cont.sensors["1920x1080hover"].owner
	nineteenten = cont.sensors["1920x1200hover"].owner

	Highover = cont.sensors["highhover"].positive
	Lowover = cont.sensors["lowhover"].positive
	Saveover = cont.sensors["saveover"].positive
	Returnover = cont.sensors["returnover"].positive
	tensixeightover = cont.sensors["1024x768hover"].positive
	elevensixfourover = cont.sensors["1152x864hover"].positive
	twelvesixeightover = cont.sensors["1280x768hover"].positive
	twelvezeroover = cont.sensors["1280x800hover"].positive
	twelvetwofourover = cont.sensors["1280x1024hover"].positive
	thirteensixeightover = cont.sensors["1366x768hover"].positive
	fourteentenover = cont.sensors["1440x900hover"].positive
	sixteenfivezeroover = cont.sensors["1680x1050hover"].positive
	nineteenzeroover = cont.sensors["1920x1080hover"].positive
	nineteentenover = cont.sensors["1920x1200hover"].positive

	up = cont.sensors["up"].positive or cont.sensors["joyup"].positive
	left = cont.sensors["left"].positive or cont.sensors["joyleft"].positive
	right = cont.sensors["right"].positive or cont.sensors["joyright"].positive
	down = cont.sensors["down"].positive or cont.sensors["joydown"].positive

	if Highover:
		High['selected']=True
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
		tensixeight['selected']=False
		elevensixfour['selected']=False
		twelvesixeight['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
	if Lowover:
		Low['selected']=True
		High['selected']=False
		Save['selected']=False
		Return['selected']=False
		tensixeight['selected']=False
		elevensixfour['selected']=False
		twelvesixeight['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
	if Saveover:
		Save['selected']=True
		High['selected']=False
		Low['selected']=False
		Return['selected']=False
		tensixeight['selected']=False
		elevensixfour['selected']=False
		twelvesixeight['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
	if Returnover:
		Return['selected']=True
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		tensixeight['selected']=False
		elevensixfour['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
	if tensixeightover:
		tensixeight['selected']=True
		elevensixfour['selected']=False
		twelvesixeight['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if elevensixfourover:
		elevensixfour['selected']=True
		tensixeight['selected']=False
		twelvesixeight['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if twelvesixeightover:
		twelvesixeight['selected']=True
		elevensixfour['selected']=False
		tensixeight['selected']=False
		twelvezero['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if twelvezeroover:
		twelvezero['selected']=True
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		twelvetwofour['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if twelvetwofourover:
		twelvetwofour['selected']=True
		twelvezero['selected']=False
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		thirteensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if thirteensixeightover:
		thirteensixeight['selected']=True
		twelvetwofour['selected']=False
		twelvezero['selected']=False
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		fourteenten['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if fourteentenover:
		fourteenten['selected']=True
		thirteensixeight['selected']=False
		twelvetwofour['selected']=False
		twelvezero['selected']=False
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		sixteenfivezero['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if sixteenfivezeroover:
		sixteenfivezero['selected']=True
		fourteenten['selected']=False
		thirteensixeight['selected']=False
		twelvetwofour['selected']=False
		twelvezero['selected']=False
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		nineteenzero['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if nineteenzeroover:
		nineteenzero['selected']=True
		sixteenfivezero['selected']=False
		fourteenten['selected']=False
		thirteensixeight['selected']=False
		twelvetwofour['selected']=False
		twelvezero['selected']=False
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		nineteenten['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False
	if nineteentenover:
		nineteenten['selected']=True
		nineteenzero['selected']=False
		sixteenfivezero['selected']=False
		fourteenten['selected']=False
		thirteensixeight['selected']=False
		twelvetwofour['selected']=False
		twelvezero['selected']=False
		twelvesixeight['selected']=False
		elevensixfour['selected']=False
		tensixeight['selected']=False
		High['selected']=False
		Low['selected']=False
		Save['selected']=False
		Return['selected']=False


	if High['selected']==True:
		if up and own['wait']>=.2:
			Save['selected']=True
			High['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			Low['selected']=True
			High['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			tensixeight['selected']=True
			High['selected']=False
			own['wait'] =0
	if Low['selected']==True:
		if up and own['wait']>=.2:
			High['selected']=True
			Low['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			Save['selected']=True
			Low['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			tensixeight['selected']=True
			Low['selected']=False
			own['wait'] =0
	if Save['selected']==True:
		if up and own['wait']>=.2:
			Low['selected']=True
			Save['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			High['selected']=True
			Save['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			Return['selected']=True
			Save['selected']=False
			own['wait'] =0
	if Return['selected']==True:
		if up and own['wait']>=.2:
			Low['selected']=True
			Return['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			High['selected']=True
			Return['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			Save['selected']=True
			Return['selected']=False
			own['wait'] =0
	if tensixeight['selected']==True:
		if up and own['wait']>=.2:
			nineteenten['selected']=True
			tensixeight['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			elevensixfour['selected']=True
			tensixeight['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			thirteensixeight['selected']=True
			tensixeight['selected']=False
			own['wait'] =0
	if elevensixfour['selected']==True:
		if up and own['wait']>=.2:
			tensixeight['selected']=True
			elevensixfour['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			twelvesixeight['selected']=True
			elevensixfour['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			fourteenten['selected']=True
			elevensixfour['selected']=False
			own['wait'] =0
	if twelvesixeight['selected']==True:
		if up and own['wait']>=.2:
			elevensixfour['selected']=True
			twelvesixeight['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			twelvezero['selected']=True
			twelvesixeight['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			sixteenfivezero['selected']=True
			twelvesixeight['selected']=False
			own['wait'] =0
	if twelvezero['selected']==True:
		if up and own['wait']>=.2:
			twelvesixeight['selected']=True
			twelvezero['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			twelvetwofour['selected']=True
			twelvezero['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			nineteenzero['selected']=True
			twelvezero['selected']=False
			own['wait'] =0
	if twelvetwofour['selected']==True:
		if up and own['wait']>=.2:
			twelvezero['selected']=True
			twelvetwofour['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			thirteensixeight['selected']=True
			twelvetwofour['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			nineteenten['selected']=True
			twelvetwofour['selected']=False
			own['wait'] =0
	if thirteensixeight['selected']==True:
		if up and own['wait']>=.2:
			twelvetwofour['selected']=True
			thirteensixeight['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			fourteenten['selected']=True
			thirteensixeight['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			High['selected']=True
			thirteensixeight['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			tensixeight['selected']=True
			thirteensixeight['selected']=False
			own['wait'] =0
	if fourteenten['selected']==True:
		if up and own['wait']>=.2:
			thirteensixeight['selected']=True
			fourteenten['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			sixteenfivezero['selected']=True
			fourteenten['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			High['selected']=True
			fourteenten['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			elevensixfour['selected']=True
			fourteenten['selected']=False
			own['wait'] =0
	if sixteenfivezero['selected']==True:
		if up and own['wait']>=.2:
			fourteenten['selected']=True
			sixteenfivezero['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			nineteenzero['selected']=True
			sixteenfivezero['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			High['selected']=True
			sixteenfivezero['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			twelvesixeight['selected']=True
			sixteenfivezero['selected']=False
			own['wait'] =0
	if nineteenzero['selected']==True:
		if up and own['wait']>=.2:
			sixteenfivezero['selected']=True
			nineteenzero['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			nineteenten['selected']=True
			nineteenzero['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			High['selected']=True
			nineteenzero['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			twelvezero['selected']=True
			nineteenzero['selected']=False
			own['wait'] =0
	if nineteenten['selected']==True:
		if up and own['wait']>=.2:
			nineteenzero['selected']=True
			nineteenten['selected']=False
			own['wait'] =0
		if down and own['wait']>=.2:
			tensixeight['selected']=True
			nineteenten['selected']=False
			own['wait'] =0
		if right and own['wait']>=.2:
			High['selected']=True
			nineteenten['selected']=False
			own['wait'] =0
		if left and own['wait']>=.2:
			twelvetwofour['selected']=True
			nineteenten['selected']=False
			own['wait'] =0